name: Update Submodules

on:
  repository_dispatch:
    types: [update-submodules]
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive

      - name: Update Submodules
        run: |
          git submodule update --remote --recursive

      - name: Commit and Push Changes
        run: |
          git config user.name "NeverLiie Bot"
          git config user.email "bot@neverliie.com"

          MODULE_NAME="${{ github.event.client_payload.module_name }}"
          if [ -z "$MODULE_NAME" ]; then MODULE_NAME="all"; fi

          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "chore: update submodule $MODULE_NAME to latest branch"
            git push
          else
            echo "No changes detected."
          fi
